# Generated by Django 2.0.2 on 2018-11-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='task',
            field=models.CharField(help_text='Enter what you have to do', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='todo',
        ),
    ]
